name: tartibat
description: Furniture marketplace application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # Storage
  shared_preferences: ^2.2.3

  # UI
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  cupertino_icons: ^1.0.8


  
  # For ZainCash WebView (when implementing)
  webview_flutter: ^4.4.2
  
  # For HTTP requests to backend
  dio: ^5.4.0
  
  # For phone call functionality
  url_launcher: ^6.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/lang/
